### ISSUE TITLE
MockClient verifyMembership error

### ISSUE THREAD

**Issue by yoshidan** [hyperledger-labs/yui-ibc-solidity#165] opened 2023-03-22 15:10 UTC
The proof commitment for MsgRecvPacket  uses `sha256 + sha256 `.

https://github.com/hyperledger-labs/yui-ibc-solidity/blob/64b95470cabe3b660c6e8d36ea58bf85b5e23dfa/pkg/relay/ethereum/chain.go#L229

https://github.com/cosmos/ibc-go/blob/12c00ec85c1238a0b9075a14593485c60f0da729/modules/core/04-channel/types/packet.go#L19

On the other hand, IBCPacket uses `sha256` + `sha256` and  MockClient verifyMembership further performs `sha256`, which always seems to cause an error. In fact, it failed in my environment.

https://github.com/hyperledger-labs/yui-ibc-solidity/blob/64b95470cabe3b660c6e8d36ea58bf85b5e23dfa/contracts/core/04-channel/IBCPacket.sol#L113-L120
https://github.com/hyperledger-labs/yui-ibc-solidity/blob/64b95470cabe3b660c6e8d36ea58bf85b5e23dfa/contracts/clients/MockClient.sol#L149

It looks like we should'n use `sha256` for `verifyMembership` in MockClient, but it is still an error because `sha256` is used in `yui-relayer` for connection and channel.
https://github.com/hyperledger-labs/yui-relayer/blob/d4cc52059626e9dd86433dbd78de0c40fba87f5b/provers/mock/prover.go#L159

As a tentative response, I was able to prevent the error by modifying MockClient's `verifyMembership` as follows.

```
//before 
return sha256(value) == proof.toBytes32(0);

//after
bytes32 v = value.toBytes32(0); // for packet
bytes32 s = sha256(value); // for connection and channel
bytes32 p = proof.toBytes32(0);
return s == p; || v == p;
```

**Comment by yoshidan** [comment] 2023-03-23 08:16
We are closing this issue because we have found that this is a problem with older versions and that the latest version behaves differently.

**Comment by yoshidan** [comment] 2023-03-23 08:48
This is

**Comment by bluele** [comment] 2023-03-24 01:55
I think the problem is that the mock-client does not support [the generic verification function](https://github.com/cosmos/ibc/pull/687).
https://github.com/datachainlab/ibc-mock-client/blob/main/modules/light-clients/xx-mock/types/client_state.go#L225

The property of being able to verify commtiment in the same method, independent of the commitment path, would be important to support some applications (e.g. https://github.com/cosmos/ibc/tree/main/spec/app/ics-031-crosschain-queries)

**Comment by bluele** [comment] 2023-05-10 06:10
I close this issue since already opened the issue in ibc-mock-client: https://github.com/datachainlab/ibc-mock-client/issues/7

**Closed by bluele** 2023-05-10 06:10 UTC
